from enum import Enum


class StatisticsMarks(Enum):
    """Labels for statistics about fixer"""

    SINGLE_NUMBER_UNIT_SENTENCE = 0
    MULTIPLE_NUMBER_UNIT_SENTENCE = 1
    CORRECT_NUMBER_UNIT = 2
    CORRECT_NUMBER_WRONG_UNIT = 3
    WRONG_NUMBER_CORRECT_UNIT = 4
    WRONG_NUMBER_UNIT = 5
    DECIMAL_SEPARATOR_PROBLEM = 6
    DIFFERENT_COUNT_NUMBERS_UNITS = 7
